/** Declaration file generated by dts-gen */

export = vue_inline_svg;

declare const vue_inline_svg: {
    InlineSvgComponent: {
        data: any;
        inheritAttrs: boolean;
        methods: {
            download: any;
            getSource: any;
            getSvgAttrs: any;
            getSvgContent: any;
        };
        mounted: any;
        props: {
            keepDuringLoading: {
                default: boolean;
                type: any;
            };
            src: {
                required: boolean;
                type: any;
            };
            title: {
                type: any;
            };
            transformSource: {
                default: any;
                type: any;
            };
        };
        render: any;
        watch: {
            src: any;
        };
    };
    InlineSvgPlugin: {
        install: any;
    };
    default: {
        data: any;
        inheritAttrs: boolean;
        methods: {
            download: any;
            getSource: any;
            getSvgAttrs: any;
            getSvgContent: any;
        };
        mounted: any;
        props: {
            keepDuringLoading: {
                default: boolean;
                type: any;
            };
            src: {
                required: boolean;
                type: any;
            };
            title: {
                type: any;
            };
            transformSource: {
                default: any;
                type: any;
            };
        };
        render: any;
        watch: {
            src: any;
        };
    };
};

