name: Create Release

on:
    push:
        tags:
            - 'v*'  # Runs automatically when a new tag is pushed
    workflow_dispatch:  # Allows manual runs

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0  # Ensure all tags are available

            -   name: Get previous tag
                id: previous_tag
                run: |
                    TAGS=($(git tag --sort=-creatordate))
                    CURRENT="${{ github.ref_name }}"
                    PREV=""
                    for i in "${!TAGS[@]}"; do
                      if [[ "${TAGS[i]}" == "$CURRENT" && $i -lt $((${#TAGS[@]} - 1)) ]]; then
                        PREV="${TAGS[i+1]}"
                        break
                      fi
                    done
                    echo "previous=$PREV" >> $GITHUB_ENV

            -   name: Create GitHub Release
                env:
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    TAG_NAME=${{ github.ref_name }}
                    PREV_TAG=${{ env.previous }}

                    if [[ -z "$PREV_TAG" ]]; then
                      echo "No previous tag found. Skipping release."
                      exit 1
                    fi

                    COMPARE_URL="https://github.com/${{ github.repository }}/compare/${PREV_TAG}...${TAG_NAME}"
                    CHANGELOG_URL="https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md"

                    gh release create "$TAG_NAME" \
                      --title "$TAG_NAME" \
                      --notes "[Compare changes]($COMPARE_URL)\n\n[Full changelog](CHANGELOG_URL)"
